### ISSUE TITLE
Getting Error when using Loading component

### ISSUE THREAD

**Issue by naveensky** [ownego/polaris-vue#193]
I am trying to use the Loading component at https://ownego.github.io/polaris-vue/?path=/docs/components-loading--loading. I am not sure if I am using it correctly, can you help me with this please

This is my layout file code
``` 
<template>
  <AppProvider>
    <Loading v-if="isActive" />
    <slot></slot>
  </AppProvider>
</template>
```

This is the error I am getting
``` error
polaris-vue.es.js?v=ea344ad5:18363 Uncaught (in promise) TypeError: startLoading is not a function
    at polaris-vue.es.js?v=ea344ad5:18363:7
    at runtime-core.esm-bundler.js:2757:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2731:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:359:46)
    at flushJobs (runtime-core.esm-bundler.js:413:9)
```

**Comment by naveensky** [comment]
A quick note, my bad at using the component. The correct way to use the component is following

```
<Frame>
   <Loading v-if="!isActive"></Loading>
</Frame>
```
